### ISSUE TITLE
Feature checklist

### ISSUE THREAD

**Issue by kvakvs** [kvakvs/vemdog#1]
## Backend
- [x] Collect process-related traces (send, receive, link, exit, spawn)
- [ ] Collect scheduler related traces (in, out, exiting, exited)
- [ ] Collect GC-related events
- [ ] Collect pattern/call traces (call, return)
- [ ] Backend API to return blocks of data per pid and per time interval
- [ ] Good timestamps linked to wall clock

## Frontend
- [x] Load JSON from disk and display as a diagram
- [ ] Load JSON from backend
- [ ] Load pieces of JSON one trace selection per pid (performance?)
- [x] Show/hide pids to improve visibility
- [x] Zoom/scroll the picture
- [ ] Save SVG file
- [ ] Display message types:
  - [x] Process-related (Send, receive, link, exit, spawn)
  - [ ] Scheduler-related (in, out, exiting, exited)
  - [ ] GC related events
  - [ ] Pattern/Call related (call, return)
- [ ] Sliding window showing limited time interval of the trace data. Allow to expand/shrink by 5 seconds?
